### ISSUE TITLE
Middleware components cannot be resolved when using AttachToComponentRegistration

### ISSUE THREAD

**Issue by holgerleichsenring** [autofac/Autofac.AspNetCore#1]
I would like to use an ExceptionMiddleware that looks like this:

```csharp
public class ExceptionHandlingMiddleware
{
   private readonly RequestDelegate _next;
   private readonly ILogger _logger;

   public ExceptionHandlingMiddleware(RequestDelegate next, ILogger logger)
   {
      _next = next;
      _logger = logger;
      _logger.Debug();
   }

   public async Task Invoke(HttpContext context /* other scoped dependencies */)
   {
      _logger.Debug();
      try
      {
         await _next(context);
      }
      catch (Exception ex)
      {
         _logger.Error(ex);
         await HandleExceptionAsync(context, ex);
      }
}
```
I would like to inject the logger directly into the middleware. That does work well as long as the registration of the implementation for ILogger is available in the container. When I do want to resolve it via runtime to catch the type of the class the logger is created for, it stops working. This is done like the following (code is incomplete but should show the issue in question).

```csharp
protected override void AttachToComponentRegistration(IComponentRegistry componentRegistry,
IComponentRegistration registration)
{
   registration.Preparing += Registration_Preparing;
}

private static void Registration_Preparing(object sender, PreparingEventArgs e)
{
   var t = e.Component.Activator.LimitType;

   e.Parameters = e.Parameters.Union(
   new[]
   {
      new ResolvedParameter(
         (p, i) => p.ParameterType == typeof(ILogger),
         (p, i) => new Logger(t))
      });
   }
}
```
Is there any possibility to let autofac take over the instantiation of middlewares as it can do with controllers?

**Comment by tillig** [comment]
I'm on vacation and only have a phone available. I know the way controllers work by default is that individual parameters get resolved from the constructor rather than the whole controller instance getting resolved from the container. That's why property injection on controllers doesn't work unless you do `ControllersAsServices`.

I'm _guessing_ that's how it works for middleware, too, but I don't have the ability to look that up for you right now. It might be a research item you can take on. Good question for the ASP.NET team and/or opportunity to spelunk through that code.

The pattern I've seen in other places is to inject the logger factory and use the factory to get the logger rather than trying to inject the logger itself. Either that or inject a generic `ILogger<T>` to avoid having to do what you're doing.

Sorry I can't provide a better answer.

**Comment by holgerleichsenring** [comment]
Thanks for your lightning fast answer!
 
I did have the ```ILogger<T>``` already in mind, but it felt a little redundant as the same information could be resolved at runtime. The same is true for ```LoggerFactory``` approach as it needs slightly more knowledge in classes and changes the most simple pattern where ```ILogger``` can just be injected and used instead of calling a factory for getting that very instance. Actually all thoughts for making logging a hurdle-free and minimum effort implementation.

I know that is complaining on a pretty high level ;-).

I'll ask ASP.NET team for advice. As being said, many thanks, enjoy your vacation!
